site_name: Inlay
repo_url: https://lab.civicrm.org/extensions/inlay
site_description: 'About the Inlay API'
site_author: 'Rich Lott / Artful Robot'
theme:
  name:
    material

nav:
- Home: index.md
- Tutorials: tutorial/index.md
- How To: howto/index.md
- Discussion:
  - About: discussion/index.md
  - Proxying: discussion/proxy.md
  - Generic Sign-up: discussion/signup.md
- Reference: reference/index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
