<?php

/**
 * @file
 * Open Collective Commerce.
 */

use Drupal\opencollective_commerce\Service\SetupGuidanceInterface;

/**
 * Implements hook_theme().
 */
function opencollective_commerce_theme($existing, $type, $theme, $path) {
  return [
    'opencollective_commerce_status_report' => [
      'variables' => [
        'title' => t('Status Details'),
        'grouped_requirements' => [],
        'requirements' => [],
      ],
    ],
    'opencollective_commerce_status_action' => [
      'render element' => 'element',
      'variables' => [
        'description' => NULL,
        'action_title' => NULL,
        'action_url' => NULL,
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK.
 */
function template_preprocess_opencollective_commerce_status_report(&$variables) {
  $variables['grouped_requirements'] = [
    'error' => [
      'type' => 'error',
      'title' => t('Errors'),
      'items' => [],
    ],
    'warning' => [
      'type' => 'warning',
      'title' => t('Warnings'),
      'items' => [],
    ],
    'checked' => [
      'type' => 'checked',
      'title' => t('Checked'),
      'items' => [],
    ],
  ];

  foreach ($variables['requirements'] as $requirement) {
    switch ($requirement['severity']) {

      case SetupGuidanceInterface::REQUIREMENT_ERROR:
        $variables['grouped_requirements']['error']['items'][] = $requirement;
        break;

      case SetupGuidanceInterface::REQUIREMENT_WARNING:
        $variables['grouped_requirements']['warning']['items'][] = $requirement;
        break;

      case SetupGuidanceInterface::REQUIREMENT_OK:
      //case SetupGuidance::REQUIREMENT_INFO:
        $variables['grouped_requirements']['checked']['items'][] = $requirement;
        break;
    }
  }
}

/**
 * Implements template_preprocess_HOOK.
 */
function template_preprocess_opencollective_commerce_status_action(&$variables) {
  $variables['element'] = [
    '#type' => 'container',
    '#attributes' => [
      'style' => 'display: flex; justify-content: space-between;',
    ],
    'description' => [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => $variables['description'],
    ],
    'action' => [
      '#type' => 'container',
      'link' => [
        '#type' => 'link',
        '#title' => $variables['action_title'],
        '#url' => $variables['action_url'],
        '#attributes' => [
          'class' => ['button'],
        ],
      ],
    ],
  ];
}
