<?php

/**
 * @file
 * Kin theme file.
 */

/*
function kin_views_pre_render(&$view){
    //echo '<pre>';
    print 'HELLO ' . $view->name;
    //echo '</pre>'
  //if($view->name == 'view_contributions_block_1'){
    if(empty($view->result) && isset($view->exposed_widgets)){
        $view->exposed_widgets = FALSE;
      }
  //}
}
*/

function kin_preprocess_html(&$variables) {

    $route = \Drupal::routeMatch();
    $user = \Drupal::currentUser();

    //$route_parts = explode('.', $route->getRouteName());
    $route_parts = explode('/', \Drupal::requestStack()->getCurrentRequest()->getPathInfo());

    $is_front = \Drupal::service('path.matcher')->isFrontPage();

    $variables['attributes']['class'][] = $is_front ? 'frontpage' : 'not-frontpage';

    if (in_array('taxonomy_term', $route_parts)) {
        $variables['attributes']['class'][] = 'taxonomy-term--page';
    }

    if (in_array('node', $route_parts)) {
        $variables['attributes']['class'][] = 'node--page';
    }

    $variables['attributes']['class'][] = 'page--' . implode('-', $route_parts);

    $variables['attributes']['class'][] = $user->id() ? 'user-authenticated' : 'user-anonymous';
}

function xxxkin_preprocess_comment(array &$variables) {
  /** @var \Drupal\comment\CommentInterface $comment */
  $comment = $variables['comment'];

  // Format the changed date (last updated)
  $variables['date'] = \Drupal::service('date.formatter')->format(
    $comment->getChangedTime(),
    'custom',
    'd/m/Y H:i'
  );

  // Optional: log to confirm it's using changed date
  //\Drupal::logger('kin')->notice('Overriding comment date to changed date: @date', ['@date' => $variables['date']]);
}

function kin_preprocess_node(array &$variables) {
  $node = $variables['node'];

  // Expose the changed date in a formatted way
  $variables['changed_date'] = \Drupal::service('date.formatter')->format(
    $node->getChangedTime(),
    'custom',
    'd/m/Y H:i'
  );
}
