riddler.riddle.*:
  type: config_entity
  label: Riddle
  mapping:
    id:
      type: string
      label: ID
    uuid:
      type: string
    question:
      type: label
      label: 'Question'
    solution:
      type: text
      label: 'Solution'
    hint:
      type: label
      label: 'Hint'
