_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 10
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  node_article_form: false
  node_faq_form: false
  node_home_page_form: false
  node_kin_group_page_form: false
  node_member_page_form: false
  node_open_collective_functionality_form: false
  node_page_form: false
  node_post_form: false
  comment_comment_form: false
