_core:
  default_config_hash: o7UdhCuEHWPn7Pz1c9KT7W818Cvg9EMVd2Gay1qKKPk
b5_body_schema: none
b5_body_bg_schema: secondary
b5_navbar_schema: none
b5_navbar_bg_schema: primary
b5_footer_schema: none
b5_footer_bg_schema: primary
b5_top_container: container
b5_top_container_config: "container|fixed\r\ncontainer-fluid m-0 p-0 g-0|fluid"
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://KIN.coop_0824_logo_Brandmark - full colour (1).png'
favicon:
  use_default: 0
  path: 'public://KIN.coop_0824_logo_Brandmark - full colour.png'
  mimetype: image/png
subtheme_folder: themes/custom
subtheme_name: 'B5 subtheme'
subtheme_machine_name: b5subtheme
