_core:
  default_config_hash: 49YbBgbzijluEX9SdUVY8jVLCDBWYa-LvZjZguWVaQM
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://KIN.coop_0824_logo_Brandmark - full colour-1.png'
  use_default: false
container: container
library:
  js_loading: ui_suite_bootstrap/framework_js
  css_loading: ''
ui_styles_entity_status_unpublished:
  selected:
    colors_background_color: bg-danger-subtle
ui_styles_regions:
  sidebar_first:
    selected:
      colors_background_color: bg-light
      spacing_padding: p-3
  sidebar_second:
    selected:
      colors_background_color: bg-light
      spacing_padding: p-3
