_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: maillog
  formatter: symfony_mailer
modules:
  webform:
    none:
      sender: maillog
      formatter: webform_php_mail
