_core:
  default_config_hash: I8SHIpIhPwREqOfhpKYny_3PbpnwIq0U8Zx409hP2L0
langcode: en-gb
enable_notifications: true
notify_by_default: true
notify_when_using: 'no'
number_of_seconds_considered_away: 120
hide_recipient_field_when_prefilled: true
create_message_label: 'Create Message'
save_message_label: Send
ban_mode: passive
ban_message: 'User is unable to receive your message'
ban_label: Block
unban_label: Unblock
ban_page_label: 'Block / Unblock users'
autofocus_enable: true
keys_send: 'Enter, 13'
remove_css: false
