_core:
  default_config_hash: FEwQLW1wXW7fiJdG1B2bxW1c_-k6w-r-3V3bSsW6PqM
auto_redirect: true
wildcard_enabled: false
passthrough_querystring: true
default_status_code: 301
warning: false
route_normalizer_enabled: true
ignore_admin_path: false
access_check: false
