opencollective_webhooks.settings:
  type: config_object
  label: 'Open Collective Webhook settings.'
  mapping:
    incoming_webhook_secret:
      type: string
      label: 'Incoming Webhooks Secret'
    poll_access_token_lifespan:
      type: integer
      label: 'Poll Access Token Lifespan'
    poll_length:
      type: integer
      label: 'Poll Length'
    debug_mode:
      type: boolean
      label: 'Debug Mode'
