# Based on: https://git.drupalcode.org/project/gitlab_templates/-/blob/1.3.11/gitlab-ci/template.gitlab-ci.yml?ref_type=tags
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"
################
# Pipeline configuration variables are defined with default values and descriptions in the file
# https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
# Uncomment the lines below if you want to override any of the variables. The following is just an example.
################
variables:
  SKIP_ESLINT: '1'
  OPT_IN_TEST_NEXT_MAJOR: '1'
  _CURL_TEMPLATES_REF: 'main'

  # Match with the "paragraphs" module setup.
  # https://git.drupalcode.org/project/paragraphs/-/blob/8.x-1.x/.gitlab-ci.yml?ref_type=heads#L51
  _PHPUNIT_CONCURRENT: '1'
  OPT_IN_TEST_PREVIOUS_MINOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_MAX_PHP: 1
