front_page.settings:
  type: config_object
  label: Front page settings
  mapping:
    enabled:
      type: boolean
      label: Front page override enabled
    disable_for_administrators:
      type: boolean
      label: Disable front page override for administrators
    home_link_path:
      type: path
      label: The home link path
    roles:
      type: sequence
      label: Overrides per role
      sequence:
        type: front_page.settings.role
        label: Front page role

front_page.settings.role:
  type: mapping
  label: Role overrides
  mapping:
    enabled:
      type: boolean
      label: Enabled
    weight:
      type: integer
      label: Weight
    path:
      type: path
      label: Redirect path
